# Generated by Django 4.2.4 on 2023-11-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='contact_number',
        ),
    ]
