# Generated by Django 4.2.4 on 2023-11-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feetype_audiencetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencetype',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_types', to='api.feetype'),
        ),
    ]
