# Generated by Django 4.2.4 on 2023-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
