# Generated by Django 4.2.4 on 2023-11-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audiencetype_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencetype',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiencetype',
            name='price',
            field=models.FloatField(),
        ),
    ]
