# Generated by Django 4.2.4 on 2023-11-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_locationimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='location_service/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accommodation')),
            ],
        ),
    ]
