# Generated by Django 4.2.4 on 2023-12-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_customfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='max_fee',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='min_fee',
        ),
    ]
