# Generated by Django 4.2.4 on 2023-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_spot_fees_remove_spot_max_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
