# Generated by Django 4.2.4 on 2023-12-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_location_email_alter_location_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelItineraryLocationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelitinerary')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spot')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
