# Generated by Django 4.2.4 on 2023-12-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_location_email_alter_location_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='foodplace',
            name='tags',
            field=models.ManyToManyField(related_name='foodplaces', to='api.foodtag'),
        ),
    ]
