# Generated by Django 4.2.4 on 2023-12-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_foodtag_foodplace_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodplace',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
