# Generated by Django 4.2.4 on 2023-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='spot',
            name='max_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='spot',
            name='min_fee',
            field=models.FloatField(default=0),
        ),
    ]
