# Generated by Django 4.2.4 on 2023-11-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='spot',
            name='activity',
            field=models.ManyToManyField(related_name='spots', to='api.activity'),
        ),
    ]
