# Generated by Django 4.2.4 on 2023-12-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_modelitinerarylocationorder'),
        ('api', '0009_foodplace_closing_time_foodplace_opening_time'),
    ]

    operations = [
    ]
