# Generated by Django 4.2.4 on 2023-12-28 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20231227_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('additional_information', models.CharField(default='No Description Provided.', max_length=500)),
                ('car', models.CharField(max_length=30)),
                ('car_type', models.CharField(choices=[('1', 'Sedan'), ('2', 'Van'), ('3', 'SUV')], default=1, max_length=1)),
                ('max_capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('plate_number', models.CharField(max_length=7)),
                ('image', models.ImageField(blank=True, default='drivers/DefaultDriverImage.png', null=True, upload_to='drivers/')),
            ],
        ),
    ]
