# Generated by Django 4.2.4 on 2023-12-31 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_is_active'),
        ('api', '0012_alter_driver_contact'),
    ]

    operations = [
    ]
