# Generated by Django 4.2.4 on 2024-01-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_event_options'),
        ('api', '0015_rename_forgotpassword_passwordreset'),
    ]

    operations = [
    ]
