# Generated by Django 4.2.4 on 2024-01-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20240105_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
