# Generated by Django 4.2.4 on 2024-01-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_passwordreset_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default='09202750407', max_length=11),
        ),
    ]
