# Generated by Django 4.2.4 on 2024-01-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='admin_responded',
            field=models.BooleanField(default=False),
        ),
    ]
