# Generated by Django 4.2.4 on 2024-01-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_contactform_admin_responded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownershiprequest',
            options={'ordering': ['-timestamp']},
        ),
    ]
