# Generated by Django 4.2.4 on 2024-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_ownershiprequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reqiures_otp',
            field=models.BooleanField(default=True),
        ),
    ]
