# Generated by Django 4.2.4 on 2024-01-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_reqiures_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reqiures_otp',
            new_name='requires_otp',
        ),
    ]
